#!/usr/bin/env bash
# displays numbers from 1 to 20 except for 4, 9 and 17
num=1
while ((num<=20))
do
	case $num in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
		*)
			echo "$num";;
	esac

	((num++))
done
