#!/usr/bin/env bash
# a Bash script that gives you information about the school file
filename="school"
if [ -e "$filename" ]
then
	echo "school file exists"
	if [ ! -s "$filename" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
		if [ -f "$filename" ]
		then
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
