#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# ifconfig | grep -oP "inet \d+\.\d+\.\d+\.\d+" | grep -oP "\d+\.\d+\.\d+\.\d+"
ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
